### ISSUE TITLE
Export function

### ISSUE THREAD

**Issue by frans-snyders** [kabir-rab/master-items-viewer#3]
Please add export functionality to the extension. 
Right-click export or an export button will be good.

**Comment by RJP-DLG** [comment]
There is a work around to export... 

- Open Developer Tool and find the TABLE element for the extension
- Right click and copy OuterHTML
- Search the web for a HTML Table to Excel converter (I used https://www.convertcsv.com/html-table-to-csv.htm)
- You have two windows (input and output) copy your Clipboard into the input and generate the excel. 

Seems to work very well all be it a bit long winded.
